name: manage-azure-policy-c7084c28
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deny_Inbound_Remote_Admin_from_Internet_9ed35b7b-3b14-4542-93ad-7b9b1e4c1d2c/**'
#      - 'policies/Tag_Resource_Groups_used_for_Demos_bcfb693e-6f1c-4167-869b-3d4b04d2fab5/**'
#      - 'policies/Audit_Resources_for_Specific_Tags_d11acecd-7e84-429c-b3ee-d66b3c99a0cb/**'
#      - 'policies/Deny-AppGW-Without-WAF_Deny-AppGW-Without-WAF/**'
#      - .github/workflows/manage-azure-policy-c7084c28.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c7084c28}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deny_Inbound_Remote_Admin_from_Internet_9ed35b7b-3b14-4542-93ad-7b9b1e4c1d2c/**
          policies/Tag_Resource_Groups_used_for_Demos_bcfb693e-6f1c-4167-869b-3d4b04d2fab5/**
          policies/Audit_Resources_for_Specific_Tags_d11acecd-7e84-429c-b3ee-d66b3c99a0cb/**
          policies/Deny-AppGW-Without-WAF_Deny-AppGW-Without-WAF/**
