name: manage-azure-policy-bca9484a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Allow_only_10.4.X.X_vNet_creation_845ecfd0-7b13-4c58-b515-439c8327f2ab/**'
#      - .github/workflows/manage-azure-policy-bca9484a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_bca9484a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Allow_only_10.4.X.X_vNet_creation_845ecfd0-7b13-4c58-b515-439c8327f2ab/**
