name: manage-azure-policy-ac75ceca
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_Microsoft_IaaSAntimalware_extension_with_custom_configurations_007bd6a4-7c0a-4455-9590-36f0682c750c/**'
#      - .github/workflows/manage-azure-policy-ac75ceca.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ac75ceca}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_Microsoft_IaaSAntimalware_extension_with_custom_configurations_007bd6a4-7c0a-4455-9590-36f0682c750c/**
